var models = [
  {
    alt: "ay",
    iso_v: "Aw==",
    size: "AAFF",
    vercontrol: "AA==",
    enttype: 1,
    rfu: "AA==",
    sizeOfName: 0,
    Name: "Access",
    isize: 325,
    att: [
      {
        Class: {
          alt: "ay",
          caption: "Ау�",
          entity: "W_ISO360_LOG",
          seqName: "",
          viewName: "W_ISO360_LOG",
          TypeId:
            "KERNEL.Alternate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 1,
        Length: 0,
        bChunk: null,
      },
      {
        Class: {
          getProcedureName: "W_GET2_PKG.GET",
          distinctProcedureName: "W_GET2_PKG.GET_DISTINCT",
          putProcedureName: "",
          postProcedureName: "",
          deleteProcedureName: "",
          TypeId:
            "KERNEL.Entity, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 2,
        Length: 0,
        bChunk: null,
      },
    ],
    rezerv02: "HA==",
    Member: [
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "ID",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: false,
              updateInBase: false,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              isPK: true,
              isVisible: true,
              LabelName: "Ключ",
              Component: 0,
              DataTextField: "",
              DataValueField: "",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: false,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "ID",
      },
      {
        att: [
          {
            Class: {
              IsFiltered: true,
              ShowFilterIcon: true,
              FilterControlWidth: 100,
              KnowFunc: 1,
              IsDistinct: true,
              GetByProperty: "",
              Format: "",
              TypeId:
                "KERNEL.Filter, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 11,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Время",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: false,
              updateInBase: false,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 3,
        customAlt: null,
        name: "CREATE_DT",
      },
      {
        att: [
          {
            Class: {
              IsFiltered: true,
              ShowFilterIcon: true,
              FilterControlWidth: 100,
              KnowFunc: 1,
              IsDistinct: true,
              GetByProperty: "",
              Format: "",
              TypeId:
                "KERNEL.Filter, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 11,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "CISO",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: false,
              updateInBase: false,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "T",
      },
    ],
    lrc: 0,
  },
  {
    alt: "param",
    iso_v: "Aw==",
    size: "AAJJ",
    vercontrol: "AA==",
    enttype: 1,
    rfu: "AA==",
    sizeOfName: 0,
    Name: "Param",
    isize: 585,
    att: [
      {
        Class: {
          alt: "param",
          caption: "Парамет",
          entity: "W_PARAMETER_V",
          seqName: "PARAMETER_SEQ",
          viewName: "W_PARAMETER_V",
          TypeId:
            "KERNEL.Alternate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 1,
        Length: 0,
        bChunk: null,
      },
      {
        Class: {
          getProcedureName: "W_GET2_PKG.GET",
          distinctProcedureName: "W_GET2_PKG.GET_DISTINCT",
          putProcedureName: "",
          postProcedureName: "",
          deleteProcedureName: "",
          TypeId:
            "KERNEL.Entity, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 2,
        Length: 0,
        bChunk: null,
      },
    ],
    rezerv02: "HA==",
    Member: [
      {
        att: [
          {
            Class: {
              IsFiltered: true,
              ShowFilterIcon: true,
              FilterControlWidth: 100,
              KnowFunc: 1,
              IsDistinct: false,
              GetByProperty: "",
              Format: "",
              TypeId:
                "KERNEL.Filter, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 11,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Параметер",
              HeadWidth: 160,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              isPK: true,
              isVisible: true,
              LabelName: "Ключ",
              Component: 0,
              DataTextField: "",
              DataValueField: "",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: false,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "PARAM_NAME",
      },
      {
        att: [
          {
            Class: {
              IsFiltered: true,
              ShowFilterIcon: true,
              FilterControlWidth: 100,
              KnowFunc: 1,
              IsDistinct: false,
              GetByProperty: "",
              Format: "",
              TypeId:
                "KERNEL.Filter, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 11,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Описание",
              HeadWidth: 240,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: false,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "DESCRIPTION",
      },
      {
        att: [
          {
            Class: {
              IsFiltered: true,
              ShowFilterIcon: true,
              FilterControlWidth: 100,
              KnowFunc: 1,
              IsDistinct: false,
              GetByProperty: "",
              Format: "",
              TypeId:
                "KERNEL.Filter, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 11,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Число",
              HeadWidth: 80,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "NUMBER_VALUE",
      },
      {
        att: [
          {
            Class: {
              IsFiltered: true,
              ShowFilterIcon: true,
              FilterControlWidth: 100,
              KnowFunc: 1,
              IsDistinct: false,
              GetByProperty: "",
              Format: "",
              TypeId:
                "KERNEL.Filter, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 11,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Строка",
              HeadWidth: 80,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "STRING_VALUE",
      },
      {
        att: [
          {
            Class: {
              IsFiltered: true,
              ShowFilterIcon: true,
              FilterControlWidth: 100,
              KnowFunc: 1,
              IsDistinct: false,
              GetByProperty: "",
              Format: "",
              TypeId:
                "KERNEL.Filter, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 11,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Байт",
              HeadWidth: 80,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 4,
        customAlt: null,
        name: "RAW_VALUE",
      },
    ],
    lrc: 0,
  },
  {
    alt: "mn",
    iso_v: "Aw==",
    size: "AAJ+",
    vercontrol: "AA==",
    enttype: 1,
    rfu: "AA==",
    sizeOfName: 0,
    Name: "Menu",
    isize: 638,
    att: [
      {
        Class: {
          alt: "mn",
          caption: "Ме",
          entity: "W_MENU_V",
          seqName: "MENU_SEQ",
          viewName: "W_MENU_V",
          TypeId:
            "KERNEL.Alternate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 1,
        Length: 0,
        bChunk: null,
      },
      {
        Class: {
          getProcedureName: "W_GET2_PKG.GET",
          distinctProcedureName: "W_GET2_PKG.GET_DISTINCT",
          putProcedureName: "",
          postProcedureName: "",
          deleteProcedureName: "",
          TypeId:
            "KERNEL.Entity, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 2,
        Length: 0,
        bChunk: null,
      },
    ],
    rezerv02: "HA==",
    Member: [
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Ключ",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: true,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              isPK: true,
              isVisible: true,
              LabelName: "Ключ",
              Component: 0,
              DataTextField: "",
              DataValueField: "",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: false,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "MENU_ID",
      },
      {
        att: [
          {
            Class: {
              IsFiltered: true,
              ShowFilterIcon: true,
              FilterControlWidth: 100,
              KnowFunc: 1,
              IsDistinct: false,
              GetByProperty: "",
              Format: "",
              TypeId:
                "KERNEL.Filter, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 11,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Название",
              HeadWidth: 120,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: 50,
              defValue: "",
              notNull: true,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "NAME",
      },
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "УРЛ",
              HeadWidth: 120,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: 500,
              defValue: "",
              notNull: false,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "URL",
      },
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Родительский обьект",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "PARENT_MENU_ID",
      },
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Стиль",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: 50,
              defValue: "'text-decoration:none'",
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "STYLE",
      },
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Приоритет",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: 0,
              defValue: "1",
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "SEQ",
      },
      {
        att: [
          {
            Class: {
              IsFiltered: true,
              ShowFilterIcon: true,
              FilterControlWidth: 100,
              KnowFunc: 1,
              IsDistinct: false,
              GetByProperty: "",
              Format: "",
              TypeId:
                "KERNEL.Filter, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 11,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Таблица",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: 100,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "TABLE_NAME",
      },
    ],
    lrc: 0,
  },
  {
    alt: "accss",
    iso_v: "Aw==",
    size: "AAEa",
    vercontrol: "AA==",
    enttype: 1,
    rfu: "AA==",
    sizeOfName: 0,
    Name: "Access",
    isize: 282,
    att: [
      {
        Class: {
          alt: "accss",
          caption: "Дос�",
          entity: "W_UG_ACCESS",
          seqName: "ACCESS_SEQ",
          viewName: "W_UG_ACCESS",
          TypeId:
            "KERNEL.Alternate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 1,
        Length: 0,
        bChunk: null,
      },
      {
        Class: {
          getProcedureName: "W_GET2_PKG.GET",
          distinctProcedureName: "W_GET2_PKG.GET_DISTINCT",
          putProcedureName: "",
          postProcedureName: "",
          deleteProcedureName: "",
          TypeId:
            "KERNEL.Entity, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 2,
        Length: 0,
        bChunk: null,
      },
    ],
    rezerv02: "HA==",
    Member: [
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: false,
              HeadName: "ID",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: true,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              isPK: true,
              isVisible: true,
              LabelName: "Ключ",
              Component: 0,
              DataTextField: "",
              DataValueField: "",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: false,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "ACCESS_ID",
      },
      {
        att: [
          {
            Class: {
              IsFiltered: true,
              ShowFilterIcon: true,
              FilterControlWidth: 100,
              KnowFunc: 1,
              IsDistinct: true,
              GetByProperty: "",
              Format: "",
              TypeId:
                "KERNEL.Filter, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 11,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Название",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "NAME",
      },
    ],
    lrc: 0,
  },
  {
    alt: "accint",
    iso_v: "Aw==",
    size: "AADV",
    vercontrol: "AA==",
    enttype: 1,
    rfu: "AA==",
    sizeOfName: 0,
    Name: "AccessIntrs",
    isize: 213,
    att: [
      {
        Class: {
          alt: "accint",
          caption: "",
          entity: "W_UG_ACCESS_INTRS",
          seqName: "",
          viewName: "W_UG_ACCESS_INTRS",
          TypeId:
            "KERNEL.Alternate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 1,
        Length: 0,
        bChunk: null,
      },
      {
        Class: {
          getProcedureName: "W_GET2_PKG.GET",
          distinctProcedureName: "W_GET2_PKG.GET_DISTINCT",
          putProcedureName: "",
          postProcedureName: "",
          deleteProcedureName: "",
          TypeId:
            "KERNEL.Entity, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 2,
        Length: 0,
        bChunk: null,
      },
    ],
    rezerv02: "HA==",
    Member: [
      {
        att: [
          {
            Class: {
              InGrid: false,
              Visible: false,
              HeadName: "",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: true,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "ACCESS_ID",
      },
      {
        att: [
          {
            Class: {
              InGrid: false,
              Visible: false,
              HeadName: "",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: true,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "USER_ID",
      },
    ],
    lrc: 0,
  },
  {
    alt: "usr",
    iso_v: "Aw==",
    size: "AAUU",
    vercontrol: "AA==",
    enttype: 1,
    rfu: "AA==",
    sizeOfName: 0,
    Name: "Users",
    isize: 1300,
    att: [
      {
        Class: {
          alt: "usr",
          caption: "Пользо",
          entity: "W_USER",
          seqName: "USER_SEQ",
          viewName: "W_USER_V",
          TypeId:
            "KERNEL.Alternate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 1,
        Length: 0,
        bChunk: null,
      },
      {
        Class: {
          getProcedureName: "W_GET2_PKG.GET",
          distinctProcedureName: "W_GET2_PKG.GET_DISTINCT",
          putProcedureName: "",
          postProcedureName: "",
          deleteProcedureName: "",
          TypeId:
            "KERNEL.Entity, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 2,
        Length: 0,
        bChunk: null,
      },
      {
        Class: {
          IsLocked: true,
          GuidOfSafety: "ad76622daa4a4ad3bec90046b89cdc75",
          TypeId:
            "KERNEL.Lock, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 3,
        Length: 0,
        bChunk: null,
      },
    ],
    rezerv02: "HA==",
    Member: [
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: false,
              HeadName: "ID",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: true,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              isPK: true,
              isVisible: true,
              LabelName: "Ключ",
              Component: 0,
              DataTextField: "",
              DataValueField: "",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: false,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "USER_ID",
      },
      {
        att: [
          {
            Class: {
              IsFiltered: true,
              ShowFilterIcon: true,
              FilterControlWidth: 100,
              KnowFunc: 1,
              IsDistinct: true,
              GetByProperty: "",
              Format: "",
              TypeId:
                "KERNEL.Filter, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 11,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Логин",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              isPK: false,
              isVisible: true,
              LabelName: "Логин",
              Component: 0,
              DataTextField: "",
              DataValueField: "",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: false,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "LOGIN",
      },
      {
        att: [
          {
            Class: {
              isCrypt: true,
              TypeId:
                "KERNEL.CryptMember, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 5,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              IsFiltered: true,
              ShowFilterIcon: true,
              FilterControlWidth: 100,
              KnowFunc: 1,
              IsDistinct: true,
              GetByProperty: "",
              Format: "",
              TypeId:
                "KERNEL.Filter, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 11,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Email",
              HeadWidth: 100,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              isPK: false,
              isVisible: true,
              LabelName: "Email",
              Component: 0,
              DataTextField: "",
              DataValueField: "",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: false,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "EMAIL",
      },
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Активный",
              HeadWidth: 50,
              type: 1,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              isPK: false,
              isVisible: true,
              LabelName: "Активный",
              Component: 0,
              DataTextField: "",
              DataValueField: "",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: false,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 6,
        customAlt: null,
        name: "ACTIVE",
      },
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Удален",
              HeadWidth: 50,
              type: 1,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: false,
              updateInBase: false,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 6,
        customAlt: null,
        name: "DELETED",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              isPK: false,
              isVisible: true,
              LabelName: "Password",
              Component: 5,
              DataTextField: "",
              DataValueField: "",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: true,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 4,
        customAlt: null,
        name: "PASSWORD",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 4,
        customAlt: null,
        name: "SALT",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              SynteticMemberRef: "ListGroup",
              relatedAlt: "gp",
              relatedValueField: "GROUP_ID",
              relatedTextField: "GROUP_NAME",
              intersectionSynteticObject: "",
              intersectionAlt: "",
              TypeId:
                "KERNEL.editFormRelation, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 15,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "GROUP_ID",
      },
      {
        att: [
          {
            Class: {
              isPK: false,
              isVisible: true,
              LabelName: "ListGroup",
              Component: 1,
              DataTextField: "GROUP_ID",
              DataValueField: "GROUP_NAME",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: true,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 5,
        customAlt: "gp",
        name: "ListGroup",
      },
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Группа",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "GROUP_NAME",
      },
      {
        att: [
          {
            Class: {
              SynteticMemberRef: "ListAccess",
              relatedAlt: "accss",
              relatedValueField: "ACCESS_ID",
              relatedTextField: "NAME",
              intersectionSynteticObject: "ListAccInt",
              intersectionAlt: "accint",
              TypeId:
                "KERNEL.editFormRelation, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 15,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "ACCESS_ID",
      },
      {
        att: [
          {
            Class: {
              isPK: false,
              isVisible: true,
              LabelName: "Интерсекшен",
              Component: 1,
              DataTextField: "ACCESS_ID",
              DataValueField: "USER_ID",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: true,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 5,
        customAlt: "accint",
        name: "ListAccInt",
      },
      {
        att: [
          {
            Class: {
              isPK: false,
              isVisible: true,
              LabelName: "Доступ",
              Component: 1,
              DataTextField: "ACCESS_ID",
              DataValueField: "NAME",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: true,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 5,
        customAlt: "accss",
        name: "ListAccess",
      },
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "del",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              SynteticMemberRef: "ListAccess",
              relatedAlt: "accss",
              relatedValueField: "ACCESS_ID",
              relatedTextField: "NAME",
              intersectionSynteticObject: "ListAccInt",
              intersectionAlt: "accint",
              TypeId:
                "KERNEL.editFormRelation, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 15,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "NAME",
      },
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Доступ в редактор",
              HeadWidth: 30,
              type: 1,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 6,
        customAlt: null,
        name: "IS_TOOLS_OWNER",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "TOKEN_GUID",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: false,
              updateInBase: false,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 3,
        customAlt: null,
        name: "TOKEN_EXPIRE_DT",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: false,
              updateInBase: false,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "TOKEN_IP",
      },
    ],
    lrc: 0,
  },
  {
    alt: "gp",
    iso_v: "Aw==",
    size: "AAF3",
    vercontrol: "AA==",
    enttype: 1,
    rfu: "AA==",
    sizeOfName: 0,
    Name: "Groups",
    isize: 375,
    att: [
      {
        Class: {
          alt: "gp",
          caption: "Гру",
          entity: "W_GROUP",
          seqName: "GROUP_SEQ",
          viewName: "W_GROUP_V",
          TypeId:
            "KERNEL.Alternate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 1,
        Length: 0,
        bChunk: null,
      },
      {
        Class: {
          getProcedureName: "W_GET2_PKG.GET",
          distinctProcedureName: "W_GET2_PKG.GET_DISTINCT",
          putProcedureName: "",
          postProcedureName: "",
          deleteProcedureName: "",
          TypeId:
            "KERNEL.Entity, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 2,
        Length: 0,
        bChunk: null,
      },
    ],
    rezerv02: "HA==",
    Member: [
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Ключ",
              HeadWidth: 250,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: true,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              isPK: true,
              isVisible: true,
              LabelName: "Ключ",
              Component: 0,
              DataTextField: "",
              DataValueField: "",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: false,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "GROUP_ID",
      },
      {
        att: [
          {
            Class: {
              IsFiltered: true,
              ShowFilterIcon: true,
              FilterControlWidth: 100,
              KnowFunc: 1,
              IsDistinct: false,
              GetByProperty: "",
              Format: "",
              TypeId:
                "KERNEL.Filter, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 11,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Название",
              HeadWidth: 250,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "GROUP_NAME",
      },
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Фото",
              HeadWidth: 80,
              type: 4,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: false,
              updateInBase: false,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 4,
        customAlt: null,
        name: "BINARY",
      },
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "LOL",
              HeadWidth: 50,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "BIN",
      },
    ],
    lrc: 0,
  },
  {
    alt: "cmn",
    iso_v: "Aw==",
    size: "AAFb",
    vercontrol: "AA==",
    enttype: 1,
    rfu: "AA==",
    sizeOfName: 0,
    Name: "Comments",
    isize: 347,
    att: [
      {
        Class: {
          alt: "cmn",
          caption: "Комме�",
          entity: "W_COMMENTS",
          seqName: "W_COMMENTS_SEQ",
          viewName: "W_COMMENTS_V",
          TypeId:
            "KERNEL.Alternate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 1,
        Length: 0,
        bChunk: null,
      },
      {
        Class: {
          getProcedureName: "W_GET2_PKG.GET",
          distinctProcedureName: "W_GET2_PKG.GET_DISTINCT",
          putProcedureName: "",
          postProcedureName: "",
          deleteProcedureName: "",
          TypeId:
            "KERNEL.Entity, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 2,
        Length: 0,
        bChunk: null,
      },
    ],
    rezerv02: "HA==",
    Member: [
      {
        att: [
          {
            Class: {
              InGrid: true,
              Visible: true,
              HeadName: "Ключ",
              HeadWidth: 250,
              type: 11,
              GetByMember: "",
              IsWrap: true,
              TypeId:
                "KERNEL.GridLocate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 9,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: true,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              isPK: true,
              isVisible: true,
              LabelName: "Ключ",
              Component: 0,
              DataTextField: "",
              DataValueField: "",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: false,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "COMMENT_ID",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "TEXT",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "IMAGE_URI",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "USER_NAME",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "LAYOUT_ID",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "SHAPE_ID",
      },
    ],
    lrc: 0,
  },
  {
    alt: "vio",
    iso_v: "Aw==",
    size: "AAE/",
    vercontrol: "AA==",
    enttype: 1,
    rfu: "AA==",
    sizeOfName: 0,
    Name: "Visual_object",
    isize: 319,
    att: [
      {
        Class: {
          alt: "vio",
          caption: "Мастер для ф�",
          entity: "W_VISUAL_OBJECTS",
          seqName: "",
          viewName: "W_VISUAL_OBJECTS",
          TypeId:
            "KERNEL.Alternate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 1,
        Length: 0,
        bChunk: null,
      },
      {
        Class: {
          getProcedureName: "W_GET2_PKG.GET",
          distinctProcedureName: "W_GET2_PKG.GET_DISTINCT",
          putProcedureName: "",
          postProcedureName: "",
          deleteProcedureName: "",
          TypeId:
            "KERNEL.Entity, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 2,
        Length: 0,
        bChunk: null,
      },
    ],
    rezerv02: "HA==",
    Member: [
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: true,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              isPK: true,
              isVisible: true,
              LabelName: "Ключ",
              Component: 0,
              DataTextField: "",
              DataValueField: "",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: false,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "SHAPE_ID",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "X",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "Y",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "WIDTH",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "HEIGHT",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "COLOR",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "IS_VISIBLE",
      },
    ],
    lrc: 0,
  },
  {
    alt: "upi",
    iso_v: "Aw==",
    size: "AAE7",
    vercontrol: "AA==",
    enttype: 1,
    rfu: "AA==",
    sizeOfName: 0,
    Name: "Profile",
    isize: 315,
    att: [
      {
        Class: {
          alt: "upi",
          caption: "Профиль",
          entity: "W_USER_PROFILE",
          seqName: "",
          viewName: "W_USER_PROFILE_V",
          TypeId:
            "KERNEL.Alternate, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 1,
        Length: 0,
        bChunk: null,
      },
      {
        Class: {
          getProcedureName: "W_GET2_PKG.GET",
          distinctProcedureName: "W_GET2_PKG.GET_DISTINCT",
          putProcedureName: "",
          postProcedureName: "",
          deleteProcedureName: "",
          TypeId:
            "KERNEL.Entity, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 2,
        Length: 0,
        bChunk: null,
      },
      {
        Class: {
          Place: 2,
          TypeId:
            "KERNEL.Area, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
        },
        enumAspect: 4,
        Length: 0,
        bChunk: null,
      },
    ],
    rezerv02: "HA==",
    Member: [
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
          {
            Class: {
              isPK: true,
              isVisible: true,
              LabelName: "Ключ",
              Component: 0,
              DataTextField: "",
              DataValueField: "",
              DefaultValue: "",
              isRequered: false,
              isHideForFront: false,
              TypeId:
                "KERNEL.editForm, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 16,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "LOGIN",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "ALT",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "ORDER_STRING",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 1,
        customAlt: null,
        name: "FILTER_STRING",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "LAST_PAGE",
      },
      {
        att: [
          {
            Class: {
              readInBase: true,
              insertInBase: true,
              updateInBase: true,
              deleteInBase: false,
              maxSize: null,
              defValue: null,
              notNull: null,
              TypeId:
                "KERNEL.InBase, kernalII, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null",
            },
            enumAspect: 2,
            Length: 0,
            bChunk: null,
          },
        ],
        attLength: null,
        rezerv01: "AA==",
        atomic: 2,
        customAlt: null,
        name: "LAST_RECORD_INDEX",
      },
    ],
    lrc: 0,
  },
];

export default function getModels() {
  return models;
}
